### ISSUE TITLE
Yocto release

### ISSUE THREAD

**Issue by kasperholtze** [jeremy-prater/meta-swift#2]
I'm trying to build an image using meta-swift. However, it doesn't really seems to fit the version I tried - Sumo, Rocko, Dunfell. Versions of libraries doesn't seems to match the binary from SwiftOnARM.

Which Yocto-release will meta-swift match?

Thank you!

**Comment by jeremy-prater** [comment]
This repo is not part of the official meta-layers. Use this code per the licence.
